MQTT_Broker:
  - "3.22.44.153"
  - "1883"

MQTTSub_Topic:
  - "mqttsim/#"
  - "node-red/#"

Topic_toSMP:
  - ["mqttsim", "runID"]
  - ["mqttsim", "progress"]
  - ["mqttsim", "tload", "1"]
  - ["mqttsim", "tload", "2"]
  - ["mqttsim", "tload", "3"]
  - ["mqttsim", "tload", "4"]
  - ["mqttsim", "tload", "5"]
  - ["mqttsim", "tload", "6"]
  - ["mqttsim", "tload", "7"]
  - ["mqttsim", "tload", "8"]
  - ["mqttsim", "tload", "9"]
  - ["mqttsim", "tload", "10"]
  - ["mqttsim", "tload", "11"]
  - ["mqttsim", "tload", "12"]

Topic_toSMP_dataType:
  - "STRING"
  - "INT"
  - "FLOAT"
  - "FLOAT"
  - "FLOAT"
  - "FLOAT"  
  - "FLOAT"
  - "FLOAT"
  - "FLOAT" 
  - "FLOAT"
  - "FLOAT"
  - "FLOAT"
  - "FLOAT"
  - "FLOAT" 

SMP_Identifier:
  - "MQTT_Connector"


 